[tools]
cargo-binstall = "latest"
"cargo:cargo-dist" = "latest"
"cargo:cargo-zigbuild" = "latest"
rust = { version = "latest", components = "rust-analyzer" }
zig = "latest"

[tasks]
test = { run = "cargo-zigbuild test" }
build = { run = "cargo-zigbuild build" }
run = { run = "cargo-zigbuild run" }
